# -*- coding: utf-8 -*-
"""Preparcial Programacion de computadore I

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZE1uQIaRxR5rT6BtjrUqMRg2j27qMGHc
"""

import pandas as pd
import ipywidgets as widgets
from IPython.display import display, clear_output

from openpyxl import load_workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.worksheet.table import Table, TableStyleInfo
from openpyxl.utils import get_column_letter

try:
    from google.colab import files
    EN_COLAB = True
except ImportError:
    EN_COLAB = False


def formato_cop(valor, decimales=0):
    texto = f"{valor:,.{decimales}f}"
    texto = texto.replace(",", "X").replace(".", ",").replace("X", ".")
    return "$" + texto



turno = {
    "cajero": None,
    "tope": None,
    "recaudo_total": 0,
    "transacciones": 0,
    "activa": False,
    "motivo_cierre": None
}

detalle_actual = []
detalle_transacciones = []
reportes = []

NOMBRE_EXCEL = "caja_recaudo.xlsx"
NOMBRE_CSV_REPORTES = "reportes_turnos.csv"
NOMBRE_CSV_DETALLE = "detalle_transacciones.csv"

COLUMNAS_MONEDA_ENTERAS = ["Tope", "Recaudo_total", "Monto", "Acumulado"]
COLUMNAS_MONEDA_DECIMALES = ["Promedio_transaccion"]

BORDE_FINO = Border(
    left=Side(style="thin", color="B0B0B0"),
    right=Side(style="thin", color="B0B0B0"),
    top=Side(style="thin", color="B0B0B0"),
    bottom=Side(style="thin", color="B0B0B0")
)



def aplicar_formato_hoja(nombre_archivo, nombre_hoja, df):
    wb = load_workbook(nombre_archivo)
    ws = wb[nombre_hoja]

    if df.empty:
        wb.save(nombre_archivo)
        return

    n_filas = len(df) + 1
    n_columnas = len(df.columns)


    relleno_encabezado = PatternFill(start_color="1F4E78", end_color="1F4E78", fill_type="solid")
    for col in range(1, n_columnas + 1):
        celda = ws.cell(row=1, column=col)
        celda.fill = relleno_encabezado
        celda.font = Font(color="FFFFFF", bold=True)
        celda.alignment = Alignment(horizontal="center")
        celda.border = BORDE_FINO


    for col in range(1, n_columnas + 1):
        letra = get_column_letter(col)
        largo_max = max(df.iloc[:, col - 1].astype(str).map(len).max(), len(str(df.columns[col - 1])))
        ws.column_dimensions[letra].width = largo_max + 4


    for col in range(1, n_columnas + 1):
        nombre_col = df.columns[col - 1]
        for fila in range(2, n_filas + 1):
            celda = ws.cell(row=fila, column=col)
            if nombre_col in COLUMNAS_MONEDA_ENTERAS:
                celda.number_format = '$ #,##0'
            elif nombre_col in COLUMNAS_MONEDA_DECIMALES:
                celda.number_format = '$ #,##0.00'
            celda.alignment = Alignment(horizontal="center")
            celda.border = BORDE_FINO


    rango = f"A1:{get_column_letter(n_columnas)}{n_filas}"
    tabla = Table(displayName=f"Tabla_{nombre_hoja}", ref=rango)
    tabla.tableStyleInfo = TableStyleInfo(
        name="TableStyleMedium9",
        showFirstColumn=False, showLastColumn=False,
        showRowStripes=True, showColumnStripes=False
    )
    ws.add_table(tabla)

    ws.freeze_panes = "A2"
    wb.save(nombre_archivo)



def guardar_excel_automatico():
    columnas_reporte = ["Cajero", "Tope", "Transacciones", "Recaudo_total",
                         "Promedio_transaccion", "Motivo_cierre"]
    df_reportes = pd.DataFrame(reportes, columns=columnas_reporte)

    columnas_detalle = ["Cajero", "Num_transaccion", "Monto", "Acumulado"]
    df_detalle = pd.DataFrame(detalle_transacciones, columns=columnas_detalle)

    with pd.ExcelWriter(NOMBRE_EXCEL, engine="openpyxl") as writer:
        df_reportes.to_excel(writer, sheet_name="Reportes", index=False)
        df_detalle.to_excel(writer, sheet_name="Detalle", index=False)

    aplicar_formato_hoja(NOMBRE_EXCEL, "Reportes", df_reportes)
    aplicar_formato_hoja(NOMBRE_EXCEL, "Detalle", df_detalle)

    df_reportes.to_csv(NOMBRE_CSV_REPORTES, index=False, sep=";", encoding="utf-8-sig")
    df_detalle.to_csv(NOMBRE_CSV_DETALLE, index=False, sep=";", encoding="utf-8-sig")



cajero_input = widgets.Text(description="Cajero:", placeholder="Ej: C-102")
tope_input = widgets.FloatText(description="Tope ($):", value=0)
boton_iniciar = widgets.Button(description="Iniciar turno", button_style="primary")



monto_input = widgets.Text(description="Monto:", placeholder="Escriba el monto, o 0 / FIN para cerrar")
boton_registrar = widgets.Button(description="Registrar transaccion", button_style="success")
boton_finalizar = widgets.Button(description="Finalizar turno (FIN)", button_style="warning")



boton_csv = widgets.Button(description="Exportar CSV")
boton_excel = widgets.Button(description="Exportar Excel")

salida = widgets.Output()



def iniciar_turno(boton):
    global detalle_actual

    if not cajero_input.value.strip():
        with salida:
            clear_output()
            print("Debe indicar el nombre o codigo del cajero.")
        return

    if tope_input.value <= 0:
        with salida:
            clear_output()
            print("El tope debe ser un numero mayor que cero.")
        return

    turno["cajero"] = cajero_input.value.strip()
    turno["tope"] = tope_input.value
    turno["recaudo_total"] = 0
    turno["transacciones"] = 0
    turno["activa"] = True
    turno["motivo_cierre"] = None
    detalle_actual = []

    with salida:
        clear_output()
        print(f"Turno iniciado para el cajero {turno['cajero']}.")
        print(f"Tope asignado: {formato_cop(turno['tope'])}")

boton_iniciar.on_click(iniciar_turno)



def cerrar_turno(motivo):
    turno["activa"] = False
    turno["motivo_cierre"] = motivo

    if turno["transacciones"] > 0:
        promedio = turno["recaudo_total"] / turno["transacciones"]
    else:
        promedio = 0

    reportes.append([
        turno["cajero"], turno["tope"], turno["transacciones"],
        turno["recaudo_total"], promedio, turno["motivo_cierre"]
    ])

    guardar_excel_automatico()

    with salida:
        clear_output()
        print("===== REPORTE DE TURNO =====")
        print(f"Cajero:               {turno['cajero']}")
        print(f"Tope asignado:        {formato_cop(turno['tope'])}")
        print(f"Transacciones:        {turno['transacciones']}")
        print(f"Recaudo total:        {formato_cop(turno['recaudo_total'])}")
        print(f"Promedio/transaccion: {formato_cop(promedio, 2)}")
        print(f"Motivo de cierre:     {turno['motivo_cierre']}")
        print()
        print(f"(Guardado automaticamente en {NOMBRE_EXCEL}, con formato de tabla)")



def registrar(boton):
    if not turno["activa"]:
        with salida:
            clear_output()
            print("No hay un turno activo. Inicie turno primero.")
        return

    texto = monto_input.value.strip()

    if texto == "0" or texto.upper() == "FIN":
        cerrar_turno("Fin de cola")
        monto_input.value = ""
        return

    try:
        monto = float(texto)
    except ValueError:
        with salida:
            clear_output()
            print("Monto invalido: debe ser un numero. Intente de nuevo.")
        monto_input.value = ""
        return

    if monto <= 0:
        with salida:
            clear_output()
            print("Monto invalido: debe ser mayor que cero. Intente de nuevo.")
        monto_input.value = ""
        return

    turno["recaudo_total"] += monto
    turno["transacciones"] += 1

    fila = [turno["cajero"], turno["transacciones"], monto, turno["recaudo_total"]]
    detalle_actual.append(fila)
    detalle_transacciones.append(fila)

    guardar_excel_automatico()

    with salida:
        clear_output()
        print(f"Transaccion #{turno['transacciones']} registrada: {formato_cop(monto)}")
        print(f"Acumulado: {formato_cop(turno['recaudo_total'])}")

    if turno["recaudo_total"] >= turno["tope"]:
        cerrar_turno("Tope alcanzado")
        with salida:
            print()
            print("CAJA SUSPENDIDA: se alcanzo el tope de recaudo. Dirijase a tesoreria.")

    monto_input.value = ""

boton_registrar.on_click(registrar)



def finalizar(boton):
    if not turno["activa"]:
        with salida:
            clear_output()
            print("No hay un turno activo.")
        return
    cerrar_turno("Fin de cola")

boton_finalizar.on_click(finalizar)



def exportar_csv(boton):
    guardar_excel_automatico()
    with salida:
        clear_output()
        print("CSV actualizados:", NOMBRE_CSV_REPORTES, "y", NOMBRE_CSV_DETALLE)
    if EN_COLAB:
        files.download(NOMBRE_CSV_REPORTES)
        files.download(NOMBRE_CSV_DETALLE)

def exportar_excel(boton):
    guardar_excel_automatico()
    with salida:
        clear_output()
        print("Excel actualizado y con formato de tabla:", NOMBRE_EXCEL)
    if EN_COLAB:
        files.download(NOMBRE_EXCEL)

boton_csv.on_click(exportar_csv)
boton_excel.on_click(exportar_excel)



display(widgets.HTML("<h2>Caja de Recaudo con Tope de Seguridad</h2>"))

display(widgets.HTML("<h3>Inicio de turno</h3>"))
display(cajero_input)
display(tope_input)
display(boton_iniciar)

display(widgets.HTML("<h3>Atencion de clientes</h3>"))
display(monto_input)
display(boton_registrar)
display(boton_finalizar)

display(widgets.HTML("<h3>Exportar informacion</h3>"))
display(boton_csv)
display(boton_excel)

display(salida)